### ISSUE TITLE
a little bit confused for example of "icd9ExplainShort"

### ISSUE THREAD

**Issue by XD-DENG** [jackwasey/icd9#77]
Hi Jack, great work for this package.

A little confused about the example given for "icd9ExplainShort" in your manual.

```
> icd9ExplainShort(ahrqComorbid[[1]][1:3])
[1] "Heart failure"                        "Rheumatic heart failure (congestive)"
> icd9Explain(ahrqComorbid[[1]][1:3], brief = TRUE)
[1] "Heart failure"           "Rheumatic heart failure"
```

For these two commands, three codes were given as inputs, but the length of outputs is 2. I tried one by one, and the results were
```
> icd9ExplainShort(ahrqComorbid[[1]][1])
[1] "Rheumatic heart failure (congestive)"
> icd9ExplainShort(ahrqComorbid[[1]][2])
[1] "Heart failure"
> icd9ExplainShort(ahrqComorbid[[1]][3])
[1] "Congestive heart failure, unspecified"
```
From my understanding, the output of 
```
> icd9ExplainShort(ahrqComorbid[[1]][1:3])
```
should be 
```
[1] "Rheumatic heart failure (congestive)"    "Heart failure"   "Congestive heart failure, unspecified"
```

Is this a bug or it was some special design? Thanks.

**Comment by jackwasey** [comment]
Glad you've found it useful. There is a `doCondense` flag, which is `TRUE` by default. This prevents numerous subordinate codes being listed when a parent code encompasses them all. Using your example (in `magrittr` style):

    ahrqComorbid$CHF[1:3]  %>%  icd9ExplainShort(doCondense = FALSE)
    [1] "Heart failure"                         "Rheumatic heart failure (congestive)"  "Congestive heart failure, unspecified"

**Comment by XD-DENG** [comment]
Sure. Sorry for not looking into the arguments carefully.

But I would suggest set the default value of doCondense to be FALSE since it's a little big confusing for users. For example, I included 10 ICD-9 codes as inputs, and only 6 explanations are returned, how I can see the mapping relationship between the 10 inputs and 6 outputs? And users would intuitively expect 3 outcomes if they gave 3 inputs.

Additionally, I found that you proposed quite many issues in the issue reports. Maybe you can give a to-do list? So that other developers can see how they can help.  I would be more than happy to offer a hand on this.

**Comment by jackwasey** [comment]
Thanks for the comments. I did wonder about this. In general, I thought people would be struggling with big lists of codes (as I was), and if I was trying to 'explain' a big set of codes, I'd want the highest-level summary in most cases. An alternative would be a different function name which would call `icd9Explain` with `condense = TRUE`, then set the default to `FALSE`. However, there are already quite a lot of functions in the package. Another alternative is to consider adding a message as part of the output with icd9Explain saying what it has done, e.g.

    ahrqComorbid$CHF[1:3]  %>%  icd9ExplainShort(doCondense = FALSE)
    Note: child codes have been included in parent codes
    [1] "Heart failure"                         "Rheumatic heart failure"

I think I'd prefer the message solution, and leave the default.

Contributions of any kind, pull requests or otherwise, would be very welcome. There are many github issues for things I would like to add, but since I didn't need them, I didn't implement them. I am currently working on ICD-10 on the icd10 branch.

**Comment by XD-DENG** [comment]
Hi Jack, I agree with your idea to add a message. However it would be good to think out a way to figure out the mapping relationship between ***n*** inputs and ***m*** outputs (***m***<***n*** if child codes are included in parent codes). Or can give a summary message indicating how many child codes were "merged"? So the users like me would not be confused.

Please feel free to let me know if you need a hand on ICD-10 branch. Would be happy to be involved in. I was struggling with ICD-9 and ICD-10 codes in my last study so I know how helpful your package is to people.

**Comment by jackwasey** [comment]
Hi, I see we need to make this clearer.

I'd be delighted to accept your contributions to this, ICD-10, or anything else. I'm currently changing a lot of things in the ICD-10 branch, but if you're serious, we can co-ordinate. Writing out the Quan/Charlson ICD-10 comorbidity mappings is one discrete bit of work. Another is writing test cases for ICD-10 codes (WHO and ICD-10-CM). Is there a particular variation of ICD-9 or ICD-10 in your country which we could include?

**Comment by jackwasey** [comment]
Thanks @wmurphyrd, that's great. I already independently copied codes from the paper (not the SAS this time) for Quan/Elixhauser, so a great use of yours would be  as very thorough set of test cases, since they come from a different person and source. For Quan/Charlson, I'll use yours as the primary source, and I'll write the test cases from the Quan paper. There are some WHO vs ICD-10-CM differences, e.g. a letter appearing in the third position in ICD-10-CM, amongst other things, but overall ICD-10 seems much easier to work with than ICD-9.

**Comment by jackwasey** [comment]
by the way, the names of the categories are saved as lazy data in `icd9::elixComorbidNames`, `icd9::elixComorbidNamesAbbrev` etc, instead of needing to generate and extract them from a data frame, as you do.

**Comment by wmurphyrd** [comment]
Good to know regarding `icd9::elixComorbidNamesAbbrev`, thanks!

**Comment by jackwasey** [comment]
N.b. this function will simply be `icd_explain` in the next big release, and it will guess whether the codes are short, long, ICD-9 or ICD-10 (or you can tell it by setting the class of the input data, e.g.
`icd_explain(icd9("441"))`
This is WIP.
